version: '2'

services:

  mysql:
    ports:
      - 3306:3306
    image: mysql:5.6
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: dashboard
      MYSQL_USER: username
      MYSQL_PASSWORD: password
